FROM python:3.11-slim

RUN apt-get update && apt-get install build-essential -y
RUN pip install poetry==1.6.1

RUN poetry config virtualenvs.create false


WORKDIR /code

COPY ./pyproject.toml ./README.md ./poetry.lock* ./

COPY ./package[s] ./packages

RUN poetry install --no-interaction --no-ansi --no-root

COPY ./app ./app

RUN export CMAKE_ARGS="-DLLAMA_CUBLAS=on"
RUN poetry install --no-interaction --no-ansi

EXPOSE 8010

CMD exec uvicorn app.server:app --host 0.0.0.0 --port 8010
