
services:
  db:
    image: postgres
    restart: always
    shm_size: '2gb'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - type: bind
        source: ./data
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432/tcp"

  imam:
    depends_on: 
      - db
    image: imam-chat:latest
    restart: always
    volumes:
      - type: bind
        source: ./imam-chat/store
        target: /code/store
      - type: bind
        source: ./imam-chat/models
        target: /code/models
      - type: bind
        source: ./imam-chat/sources
        target: /code/sources
    build: ./imam-chat/
    command: uvicorn app.server:app --host 0.0.0.0 --port 8010
    ports:
      - "8010:8010/tcp"
