[tool.poetry]
name = "rag"
version = "0.1.0"
description = "RAG using local LLM, embeddings, vectorstore"
authors = [
    "Slepovichev Ivan <gurgutan@yandex.ru>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = "^0.1"
tiktoken = ">=0.5.1"
chromadb = ">=0.4.14"
gpt4all = ">=1.0.8"
beautifulsoup4 = ">=4.12.2"
langchain-text-splitters = ">=0.0.1,<0.1"
llama-cpp-python = "^0.2.56"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.21"

[tool.langserve]
export_module = "rag"
export_attr = "chain"

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
